### ISSUE TITLE
Bilingual comments?!

### ISSUE THREAD

**Issue by dandv** [molily/selectionmenu#2]
Seriously?

https://github.com/molily/selectionmenu/blob/master/copylink.js

What programmer who knows JavaScript and uses GitHub, doesn't know the basic English used in those comments?

http://www.spiegel.de/international/those-lying-germans-i-don-t-speak-much-english-a-410295.html

**Comment by molily** [comment]
This repo initially was related to three technical articles written in German, that’s why the code documentation was in German, too. The English comments were added later so non-German speakers may find it useful, too. ;)

**Comment by dandv** [comment]
OK, that explains it. Thanks :)
